import Link from 'next/link'
import { PublicShell } from '../public-shell'
import ui from '../public-brand.module.css'

export const metadata={title:'About RADVORA',description:'Learn how RADVORA is building ShieldTag as a premium, device-aware identity system with compatibility and product claims kept explicit.',alternates:{canonical:'/about'}}

export default function AboutPage(){
  return <PublicShell><main className={ui.main}>
    <section className={ui.hero}><div className={ui.heroCopy}><span className={ui.kicker}>ABOUT RADVORA</span><h1>Identity designed<br/><em>like hardware.</em></h1><p>RADVORA is building ShieldTag as a premium device identity system: one recognisable visual language adapted across phones, tablets, laptops and selected technology accessories.</p><div className={ui.actions}><Link className={ui.primary} href="/products">Explore ShieldTag →</Link><Link className={ui.secondary} href="/#shieldlab">Open ShieldLab</Link></div></div><aside className={ui.heroAside}><span>THE IDEA</span><strong>It should look like it belongs there.</strong><p>The product is positioned around proportion, finish, personalisation, identity and verification potential—not exaggerated protection claims.</p></aside></section>
    <section className={ui.section}><div className={ui.grid3}><article className={ui.panel}><span className={ui.kicker}>01 · DESIGN</span><h3>Device-aware proportions.</h3><p>Signature, Pro, Executive and Mini formats let the identity system scale with the hardware instead of forcing one badge onto every surface.</p></article><article className={ui.panel}><span className={ui.kicker}>02 · PERSONALISATION</span><h3>Finishes that relate to the device.</h3><p>Colour directions are designed to either blend with the device finish or create a controlled contrast without turning the product into a novelty sticker.</p></article><article className={ui.panel}><span className={ui.kicker}>03 · ACCOUNTABILITY</span><h3>Evidence before claims.</h3><p>Compatibility and performance statements remain separate from styling. Unvalidated claims are not promoted simply because the visual concept looks finished.</p></article></div></section>
    <section className={ui.section}><div className={ui.sectionHead}><span className={ui.kicker}>OPERATING PRINCIPLE</span><h2>Premium presentation.<br/><em>Controlled claims.</em></h2><p>RADVORA can build a strong consumer-tech identity without overstating what the product has been tested to do. Verification, compatibility and future validated specifications stay traceable and explicit.</p></div></section>
  </main></PublicShell>
}
